config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  devise_for :users
  resources :users
  resources :users, only: [:show]
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'foods/index' => 'foods#index'
  root 'foods#index'

  get 'foods/link' => 'foods#link'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :tweets
         has_many :likes, dependent: :destroy
         has_many :liked_tweets, through: :likes, source: :tweet
         has_many :comments, dependent: :destroy
         has_many :tweets, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
         validates :name, presence: true #追記
         validates :profile, length: { maximum: 200 }

         def already_liked?(tweet)
          self.likes.exists?(tweet_id: tweet.id)
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
          
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
  
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      tweet = Tweet.find(params[:tweet_id])
      comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path)
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path)
      end
    end

    private

      def comment_params
        params.require(:comment).permit(:content)
      end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

    def index
    end

    def link
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
      like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
      redirect_back(fallback_location: root_path)
    end

    def destroy
      like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
      like.destroy
      redirect_back(fallback_location: root_path)
    end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!

  def index
    @schedules = Schedule.all
  end

  def new
    @schedule= Schedule.new
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def create
    Schedule.create(schedule_parameter)
    redirect_to schedules_path
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to schedules_path, notice:"削除しました"
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(schedule_parameter)
      redirect_to schedules_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  private

  def schedule_parameter
    params.require(:schedule).permit(:title, :content, :start_time, :image)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!

    def index
        if params[:search] != nil && params[:search] != ''
          #部分検索かつ複数検索
          search = params[:search]
          @tweets = Tweet.joins(:user).where("body LIKE ? OR shop LIKE ? OR place LIKE ? OR food LIKE ? OR price LIKE ? OR name LIKE ?","%#{search}%", "%#{search}%","%#{search}%", "%#{search}%","%#{search}%","%#{search}%").page(params[:page]).per(6)
        else
          @tweets = Tweet.all.page(params[:page]).per(6)
        end
    end

    def new
        @tweet = Tweet.new
    end

    def create
        tweet = Tweet.new(tweet_params)
        tweet.user_id = current_user.id
        if tweet.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end

    def show
        @tweet = Tweet.find(params[:id])
        @comments = @tweet.comments
        @comment = Comment.new
    end
    
    def edit
        @tweet = Tweet.find(params[:id])
    end
    
    def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
          redirect_to :action => "show", :id => tweet.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to action: :index
    end

    private
     def tweet_params
        params.require(:tweet).permit(:body, :shop, :place, :food, :price, :created_at, :image, :taste, :overall, :originality, :wait)
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
      @user = User.find(params[:id]) 
    end

    #def Calender
    #  @calenders = @user.calenders.includes(:logo)
    #end

    private

    def user_params
        params.require(:user).permit(:name, :profile, :image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
      end
     
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<%= stylesheet_link_tag 'index_foods', :media => "all" %>
<div>
  <%= image_tag 'index_foods_first_photo.jpg',class:'index_foods_first'%>
    <header>
    <h1>俺の球場飯！　～神宮球場グルメ紹介～</h1>
    <div class="header-list3">
        <ul>
          <%= link_to "ログイン", tweets_path %>
          <%= link_to "新規登録", new_user_registration_path %>
          <%= link_to "球場飯投稿へ！", new_tweet_path %>
          <%= link_to "球場飯一覧へ", tweets_path %>
          <%= link_to "試合日程を確認！", schedules_path %>
        </ul>
    </div>
  </header>

    <br>
    <div class="fv">
      <h2>Concept</h2>
    </div>
    <div class="fr">
      <h2>「神宮球場の隠れた魅力」を紹介！！</h2>
    </div>
      <div class="az">
        <br>
        <br>
        <%= image_tag 'index_foods_second_photo.jpg',class:'index_foods_second'%>
          <div class="aq">
            <br>
            <p>野球場の新しい魅力の発掘。<p>
            <p>そんな想いからこのサイトを開設しました。<p>
          </div>
        </div>
      </div>
    </h2>
      <br>
      <div class="sw">
        <br>
        <br>
        <%= image_tag 'index_foods_third_photo.jpg',class:'index_foods_third'%>
          <div class="sx">
            <br>
            <p>神宮球場の新しい魅力を<p>
            <p>あなたも味わってみませんか？<p>
          </div>
        </div>
        <br>
        <br>
        <br>
        <br>
        <div class="de">
          <p>あなたのお気に入り、きっと見つかります<p>
        </div>
    </h2>

    <br>
    <br>
    <br>
    <br>
    <h2>検索タブ</h2>

    <h3>球場飯を検索</h3>
      <div class="abc">
        <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
          <%= text_field_tag :search %>
          <%= submit_tag '検索する'  %>
          <p>※検索時、数字は半角で入力してください<p>
        <% end %>
      </div>

app/views/foods/link.html.erb
My name is Geeksalon.
<%= link_to 'トップページ', foods_index_path %>
<%= link_to '一覧表示', :controller => "tweets", :action => "index" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ballparkfood</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/edit.html.erb
<%= form_with(model: @schedule, local: true) do |form| %>

  <div class="title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

　<div class="time">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>


  <div class="submit">
    <%= form.submit "編集する" %>
  </div>

<% end %>

app/views/schedules/index.html.erb
<%#<h1>Schedules#index</h1>
<p>Find me in app/views/schedules/index.html.erb</p> %>
<%= stylesheet_link_tag 'index.schedule', :media => "all" %>
<div>
  <%= image_tag 'index.schedule_photo.jpg',class:'r'%>
    <header>
      <h1>俺の球場飯！　～神宮球場グルメ紹介～</h1>
      <div class="header-list">
      <ul>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
      <%= link_to "ホームへ", foods_index_path %>
      <%= link_to "球場飯投稿へ", new_tweet_path %>
      <%= link_to "球場飯一覧へ", tweets_path %>
      </ul>
    </header>


    <h2>球場飯を検索</h2>
      <div class="w">
        <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
          <%= text_field_tag :search %>
          <%= submit_tag '検索する'  %>
          <p>※検索時、数字は半角で入力してください<p>
      </div>
    <% end %>

    <br>
    <br>
    <h2>対戦カレンダー</h2>

    <p id="notice"><%= notice %></p>

    <%#<table>
      <thead>
        <tr>
          <th>タイトル</th>
          <th>時間</th>
          <th colspan="3"></th>
        </tr>
      </thead> 

      <tbody>
        <% @schedules.each do |schedule| %>
        <%#  <tr>
            <td><%= schedule.title %></td>
        <%#    <td><%= schedule.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <%#    <td><%= link_to 'Show', schedule %></td>
        <%#    <td><%= link_to 'Edit', edit_schedule_path(schedule.id) %></td>
        <%#    <td><%= link_to 'Destroy',schedule_path(schedule.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%#  </tr>
        <% end %>
    <%#  </tbody>
    </table> %>

    <br>

    <%= link_to '日程入力', new_schedule_path %>

    <%= month_calendar events: @schedules do |date, schedules| %>
      <%= date.day %>

      <% schedules.each do |schedule| %>
        <div>
          <%= image_tag schedule.image_url, size: "80x60" if schedule.image? %>
          <p><%= link_to schedule.title, schedule %>
        </div>
      <% end %>
    <% end %>

</div>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>開始時刻</strong>
  <%= @schedule.title %>
</p>

<%#<p>
  <strong>時間</strong>
  <%= @schedule.start_time.strftime("%Y-%m-%d %H:%M") %>
</p>

<p>
  <strong>限定球場飯</strong>
  <%= @schedule.content %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>

app/views/tweets/edit.html.erb
<%= stylesheet_link_tag 'edit', :media => "all" %>
<div>
  <%= image_tag 'edit_photo.jpg',class:'a'%>

  <header>
  <h1>俺の球場飯！ ～神宮球場グルメ紹介～</h1>
  </header>
    <h3>投稿編集</h3>
    <%= form_for @tweet do |f| %>
      <div class="field">
        <p><%= f.label :body %><p>
        <%= f.text_field :body, :size => 60 %>

        <P><%= f.label :shop %><p>
        <%= f.text_field :shop, :size => 60 %>

        <p><%= f.label :place %><p>
        <%= f.select :place, 
        [["内野", "内野"],
        ["外野", "外野"],  
        ["内外野", "内外野"],
        ["球場外", "球場外"]], include_blank: "選択して下さい" %>

        <p><%= f.label :food %><p>
        <%= f.select :food, 
        [["ラーメン", "ラーメン"], 
        ["丼もの", "丼もの"], 
        ["麺類その他", "麺類その他"],
        ["カレー", "カレー"],
        ["バーガー", "バーガー"],
        ["ソフトドリンク", "ソフトドリンク"],
        ["アルコール", "アルコール"],
        ["スイーツ", "スイーツ"],
        ["その他", "その他"]], include_blank: "選択して下さい" %>
        
        <p><%= f.label :price %><p>
        <%= f.select :price, 
        [["0～500", "0～500"], 
        ["501～750", "501～750"], 
        ["751～1000", "751～1000"],
        ["1001～1250", "1001～1250"],
        ["1251～1500", "1251～1250"],
        ["1501～", "1501～"]], include_blank: "選択して下さい" %>
      </div>
      <div class="d">
        <p><h5>総合評価</h5><p>
        <div class="post_form">
        <%= f.radio_button :taste, 5 ,id: 'star1'%>
        <label for="star1"><span class="text">最高</span>★</label>

        <%= f.radio_button :taste, 4 ,id: 'star2'%>
        <label for="star2"><span class="text">良い</span>★</label>

        <%= f.radio_button :taste, 3 ,id: 'star3'%>
        <label for="star3"><span class="text">普通</span>★</label>

        <%= f.radio_button :taste, 2 ,id: 'star4'%>
        <label for="star4"><span class="text">悪い</span>★</label>

        <%= f.radio_button :taste, 1 ,id: 'star5'%>
        <label for="star5"><span class="text">最悪</span>★</label>
      </div>
      <div class="e">
        <p><h5>味</h5><p>
        <div class="post_form">
        <%= f.radio_button :overall,  5 ,id: 'star6'%>
        <label for="star6"><span class="text">最高</span>★</label>

        <%= f.radio_button :overall,  4 ,id: 'star7'%>
        <label for="star7"><span class="text">良い</span>★</label>

        <%= f.radio_button :overall, 3 ,id: 'star8'%>
        <label for="star8"><span class="text">普通</span>★</label>

        <%= f.radio_button :overall , 2 ,id: 'star9'%>
        <label for="star12"><span class="text">やや多い</span>★</label>

        <%= f.radio_button :overall , 1 ,id: 'star10'%>
        <label for="star10"><span class="text">最悪</span>★</label>
      </div>
      <div class="f">
        <p><h5>量</h5><p>
        <div class="post_form">
        <%= f.radio_button :originality,  5 ,id: 'star11'%>
        <label for="star11"><span class="text">多い</span>★</label>

        <%= f.radio_button :originality,  4 ,id: 'star12'%>
        <label for="star12"><span class="text">やや多い</span>★</label>

        <%= f.radio_button :originality, 3 ,id: 'star13'%>
        <label for="star13"><span class="text">普通</span>★</label>

        <%= f.radio_button :originality , 2 ,id: 'star14'%>
        <label for="star14"><span class="text">やや少ない</span>★</label>

        <%= f.radio_button :originality , 1 ,id: 'star15'%>
        <label for="star15"><span class="text">少ない</span>★</label>
      </div>
      <div class="g">
        <p><h5>待ち時間</h5><p>
        <div class="post_form">
        <%= f.radio_button :wait,  5 ,id: 'star16'%>
        <label for="star16"><span class="text">～5分</span>★</label>

        <%= f.radio_button :wait,  4 ,id: 'star17'%>
        <label for="star17"><span class="text">～10分</span>★</label>

        <%= f.radio_button :wait, 3 ,id: 'star18'%>
        <label for="star18"><span class="text">～15分</span>★</label>

        <%= f.radio_button :wait , 2 ,id: 'star19'%>
        <label for="star19"><span class="text">～25分</span>★</label>

        <%= f.radio_button :wait , 1 ,id: 'star20'%>
        <label for="star20"><span class="text">25～分</span>★</label>
      </div> 

      
      <div class="field">
        <%= f.label :image %>
      <%= f.file_field :image %>
      </div>
      <div class="b">
          <%= f.submit "投稿する" %>
      </div>

    <% end %>
        
        
    <div class="c">
      <%= link_to "球場飯一覧に戻る", tweets_path %>
    </div>


</div>

app/views/tweets/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<div>
  <%= image_tag 'index_photo.jpg',class:'h'%>

    <header>
        <h1>俺の球場飯！　～神宮球場グルメ紹介～</h1>
        <div class="header-list">
        <ul>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
          <%= link_to "ホームへ", foods_index_path %>
          <%= link_to "球場飯投稿へ", new_tweet_path %>
          <%= link_to "試合日程を確認する！", schedules_path %>
        </ul>
        <div class="tweets-container">
        <% if user_signed_in? %>
        <%= link_to "マイページへ", user_path(current_user.id) %>　
        <% end %>
        </div>
    </header>

    <br>

    <h3>球場飯を検索</h3>
    <div class="i">
      <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
        <%= text_field_tag :search %>
        <%= submit_tag '検索する'  %>
        <p>※検索時、数字は半角で入力してください<p>
      <% end %>
    </div>

    <br>
    <br>


    <h3>球場飯一覧</h3>
      <div class="j">
      <%= page_entries_info @tweets %>
      </div>
      
      <div class="tweets-container1">
        <% @tweets.each do |t| %>
          <div class="tweet">
            <p><%= image_tag t.image_url, size: "250x200" if t.image? %><p>
            <p><%= t.body %><p>
            <%= t.shop %>
            <%= t.place %>
            <%= t.food %>
            <%= t.price %>
            <div>
            <h2>総合評価：
            <span class="star-rating">
              <span class="star-rating-front" style="width: <%= getPercent(t.taste) %>%;">★★★★★</span>
              <span class="star-rating-back">★★★★★</span>
            </span> 
            </h2>
            </div>
            <div>
            <h2>味：
            <span class="star-rating">
              <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
              <span class="star-rating-back">★★★★★</span>
            </span>
            </h2>
            </div>
            <div>
            <h2>量：
            <span class="star-rating">
              <span class="star-rating-front" style="width: <%= getPercent(t.originality) %>%;">★★★★★</span>
              <span class="star-rating-back">★★★★★</span>
            </span>
            </h2>
            </div>
            <h2>待ち時間：
            <span class="star-rating">
              <span class="star-rating-front" style="width: <%= getPercent(t.wait) %>%;">★★★★★</span>
              <span class="star-rating-back">★★★★★</span>
            </span>
            </h2>
                  <% if user_signed_in? %>
                  <% if current_user.already_liked?(t) %>
                      <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                          <i class="fas fa-heart"></i><%= t.likes.count %>
                      <% end %>
                  <% else %>
                      <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                          <i class="far fa-heart"></i><%= t.likes.count %>
                      <% end %>
                  <% end %>
              <% else %>
                  <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>
                  <%= t.created_at %>
                  <p><%= link_to "詳細へ", tweet_path(t.id) %>
                  <% if user_signed_in? && current_user.id == t.user_id %>  
                　<%= link_to "編集する", edit_tweet_path(t.id) %>
                　<%= link_to "削除する", tweet_path(t.id), method: :delete %>
            　　  <% end %>
                </div>
                

              <% end %>
            </div>

            <div class="k">
            <%= paginate @tweets %>
            </div>
          </div>
      </div>
</div>

app/views/tweets/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>
<div>
  <%= image_tag 'show_photo.jpg',class:'l'%>

    <header>
      <h1>俺の球場飯！　～神宮球場グルメ紹介～</h1>
      <div class="header-list2">
      <ul>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
        <%= link_to "ホームへ", foods_index_path %>
        <%= link_to "球場飯投稿へ", new_tweet_path %>
        <%= link_to "試合日程を確認する！", schedules_path %>
      </ul>
    </header>
    
    <br>

    <div class="n">
    <h2>球場飯を検索</h2>
      <%= form_tag({controller:"tweets",action:"show"}, method: :get) do %>
        <%= text_field_tag :search %>
        <%= submit_tag '検索する'  %>
        <p>※検索時、数字は半角で入力してください<p>
      <% end %>
    </div>

    <br>
    <br>


    <h2>球場飯詳細・商品評価</h2>
    <div class="tweets-container3">
      <div class="tweet3">
        <p><%= image_tag @tweet.image_url, size: "300x240" if @tweet.image? %><p>
        <p><%= @tweet.body %><p>
        <p><%= @tweet.shop %>
        <%= @tweet.place %>
        <%= @tweet.food %>
        <%= @tweet.price %>
        <div>
        <h2>総合評価：
        <span class="star-rating">
          <span class="star-rating-front" style="width: <%= getPercent(@tweet.taste) %>%;">★★★★★</span>
          <span class="star-rating-back">★★★★★</span>
        </span> 
        </h2>
        </div>
        <div>
        <h2>味：
        <span class="star-rating">
          <span class="star-rating-front" style="width: <%= getPercent(@tweet.overall) %>%;">★★★★★</span>
          <span class="star-rating-back">★★★★★</span>
        </span>
        </h2>
        </div>
        <div>
        <h2>量：
        <span class="star-rating">
          <span class="star-rating-front" style="width: <%= getPercent(@tweet.originality) %>%;">★★★★★</span>
          <span class="star-rating-back">★★★★★</span>
        </span>
        </h2>
        </div>
        <div>
        <h2>待ち時間：
        <span class="star-rating">
          <span class="star-rating-front" style="width: <%= getPercent(@tweet.wait) %>%;">★★★★★</span>
          <span class="star-rating-back">★★★★★</span>
        </span>
        </h2>
        </div>

      </div>
    </div>


    <h3>口コミ</h3>
    <div class="comment-wrapper">
      
      <% @comments.each do |c| %>
        <div>
          <%= c.user.name unless c.user.blank? %>
          <br>
          <%= c.content %>
        </div>
          <br>
      <% end %>
    </div>

        <br>
        <div class="field2">
          <% if user_signed_in? %>
            <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
              <%= f.text_field :content %>
              <%= button_tag type: "submit" do %>
                <i class="far fa-comments"></i> コメントする
              <% end %>
            <% end %>
          <% end %>
        </div>
    
    <div class="q">
    <%= link_to "球場飯一覧に戻る", tweets_path %>
    <%#<%= link_to "編集する", edit_tweet_path(@tweet.id) %>
    </div>
</div>  

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'show.user', :media => "all" %>
<div>
  <%= image_tag 'show.user_photo.jpg',class:'x'%>  
    <header>
      <h1>俺の球場飯！　～神宮球場グルメ紹介～</h1>
    </header>

    
    <br>
    <h2>マイページ</h2>

    <br>
    <br>
    <h3>プロフィール</h3>
      <div class="s">
        <p>名前 : <%= @user.name %></p>
        <p>登録メアド : <%= @user.email %></p>
        <p>自己紹介 : <%= @user.profile %></p>
      </div>
    </div>

    <div class="z">
      <% if current_user.id == @user.id %>
        <%= link_to "編集する", edit_user_registration_path %>
      <% end %>
    </div>

    <br>
    <br>
    <h3>お気に入りの球場飯</h3>
      <div class="p">
        <% @user.liked_tweets.each do |t| %>
          <div class="t">
            <p><%= image_tag t.image_url, size: "150x100" if t.image? %><p>
            <p><%= t.user.name %><p>
            <%= t.body %>
          </div>
        <% end %>
      </div>
    </div>

    <br>
    <br>
    <br>
    <h3>ユーザーが味わった球場飯</h3>
      <div class="y">
        <% @user.tweets.each do |t| %>
          <div class="u">
          　<p><%= image_tag t.image_url, size: "150x100" if t.image? %><p>
            <p><%= t.body %><p>
          </div>
        <% end %>
    </div>

    <div class="o">
      <%= link_to "球場飯一覧に戻る", tweets_path %>
    </div>